version: '2'
services:
  namenode:
    image: bf16574403/hadoop-namenode
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    env_file:
      - ./hadoop.env

  datanode:
    image: bf16574403/hadoop-datanode
    depends_on:
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    ports:
      - "50075"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bf16574403/hadoop-resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: bf16574403/hadoop-nodemanager
    depends_on:
      - namenode
      - resourcemanager
    env_file:
      - ./hadoop.env

  historyserver:
    image: bf16574403/hadoop-historyserver
    container_name: historyserver
    depends_on:
      - namenode
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

  spark-master:
    image: bf16574403/spark-master
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - ./hadoop.env

  zookeeper1:
    container_name: zookeeper1
    image: bf16574403/zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888,zookeeper2:2889:3889,zookeeper3:2890:3890
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  zookeeper2:
    container_name: zookeeper2
    image: bf16574403/zookeeper
    environment:
      - ZOOKEEPER_ID=2
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888,zookeeper2:2889:3889,zookeeper3:2890:3890
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"

  zookeeper3:
    container_name: zookeeper3
    image: bf16574403/zookeeper
    environment:
      - ZOOKEEPER_ID=3
      - ZOOKEEPER_SERVERS=zookeeper1:2888:3888,zookeeper2:2889:3889,zookeeper3:2890:3890
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"

  kafka:
    image: bf16574403/kafka
    container_name: kafka
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      - ZOOKEEPER_SERVERS=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    ports:
      - "9092:9092"

  kafka-manager:
    image: bf16574403/kafka-manager
    container_name: kafka-manager
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - kafka
    environment:
      - ZK_HOSTS=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    ports:
      - "9000:9000"

#  spark-worker:
#    image: test/spark-worker
#    depends_on:
#      - spark-master
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"
#    ports:
#      - "8081:8081"
#    env_file:
#      - ./hadoop.env
