apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: datanode
  name: datanode
spec:
  ports:
  - name: datanode
    port: 50075
    targetPort: 50075
  selector:
    name: datanode
