
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: datanode
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: datanode
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: hadoop-env
        image: bf16574403/hadoop-datanode
        name: datanode
        ports:
        - containerPort: 50075
        resources: {}
#        volumeMounts:
#        - mountPath: /hadoop/dfs/data
#          name: datanode-claim0
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
#      volumes:
#      - name: datanode-claim0
#        persistentVolumeClaim:
#          claimName: datanode-claim0
status: {}
