apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: kafka-manager
  name: kafka-manager
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    name: kafka-manager
  type: NodePort
