apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  ports:
  - name: "50075"
    port: 50075
    targetPort: 50075
  selector:
    io.kompose.service: datanode
status:
  loadBalancer: {}
