apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: historyserver
  name: historyserver
spec:
  ports:
  - name: "8188"
    port: 8188
    targetPort: 8188
  selector:
    io.kompose.service: historyserver
status:
  loadBalancer: {}
