apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  ports:
  - name: "50070"
    port: 50070
    targetPort: 50070
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
