apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: zookeeper3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zookeeper3
    spec:
      containers:
      - env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVERS
          value: zookeeper1:2888:3888,zookeeper2:2889:3889,zookeeper3:2890:3890
        image: bf16574403/zookeeper
        name: zookeeper3
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        resources: {}
      restartPolicy: Always
status: {}
