apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper3
  name: zookeeper3
spec:
  ports:
  - name: "2183"
    port: 2183
    targetPort: 2181
  - name: "2890"
    port: 2890
    targetPort: 2888
  - name: "3890"
    port: 3890
    targetPort: 3888
  selector:
    io.kompose.service: zookeeper3
status:
  loadBalancer: {}
