apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spark-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: spark-master
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: hadoop-env
        image: bf16574403/spark-master
        name: spark-master
        #command: ["/bin/bash"]
        #args: ["-c", "env"]
        ports:
        - containerPort: 8080
        - containerPort: 7077
        resources: {}
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
status: {}
